### ISSUE TITLE
Can not instll rusty-rlp in windows

### ISSUE THREAD

**Issue by Jonney** [cburgdorf/rusty-rlp#15]
pip install rusty-rlp

ERROR: Could not find a version that satisfies the requirement rusty-rlp (from versions: none)
ERROR: No matching distribution found for rusty-rlp

It's windows 10

**Comment by cburgdorf** [comment]
Is this a 32bit or 64bit system?

**Comment by Jonney** [comment]
64bit
Python 3.8.5

**Comment by cburgdorf** [comment]
Mmh, that is unexpected. The binaries for Windows 64 are on pypi: https://pypi.org/project/rusty-rlp/0.1.15/#files
I don't have access to a windows machine so I'm having trouble to debug this. I'll try to find a way to help with this.

**Comment by Jonney** [comment]
pip install rusty_rlp-0.1.15-cp38-none-win_amd64.whl

ERROR: rusty_rlp-0.1.15-cp38-none-win_amd64.whl is not a supported wheel on this platform.

**Comment by Jonney** [comment]
I checked again carefully.
Windows is 64bit, but... python is 32bit.
After install python 64bit, problem resolved.
Sorry to burden you.

**Comment by cburgdorf** [comment]
Ah, that's great to hear! Thanks for letting me know!
