### ISSUE TITLE
Any chance of an amd64 build please?

### ISSUE THREAD

**Issue by helpfulBrother** [cburgdorf/rusty-rlp#18]
AMD needs some love too! 👍

**Comment by cburgdorf** [comment]
@helpfulBrother I'm currently limited to the machines that GitHub Actions provides me access to. If there's an easy way to add support, I'd be happy to review any PRs. I'm just curious did you run into installation errors installing a 3rd library such as web3.py or do you want to use `rusty-rlp` directly?

**Comment by helpfulBrother** [comment]
When running web3py I get a message advising to use rusty-rlp for better performance, when I try to install it using pip I get an error that my config (AMD) is not supported.

**Comment by cburgdorf** [comment]
Ah, alright! Thanks for clarifying. I was just worried that you were hitting an installation issue (which should be fixed) but it sounds that you are running into the *suggestion* to install `rusty-rlp` for better performance. That's fine. Looking into other support for other machine types is currently not a priority for me but I'm always open to accept PRs that add support.

**Comment by helpfulBrother** [comment]
I have no idea how to do a PR :| but understand your position. Thanks for the reply.
